spring.application.name=1792BatteryWeb
# Load Production Variables from non git file
spring.config.import=optional:file:config/env.properties

#Testing database / self hosted
#spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=health,info,mappings
management.endpoint.health.show-details=always

# Get Version from pom.xml
app.version=@project.version@

# Server Debugging
#org.apache.jasper.compiler.TldLocationsCache.level = FINE
#org.apache.jasper.servlet.TldScanner.level = FINE
#logging.level.org.springframework=DEBUG
#logging.level.org.apache.catalina=DEBUG
